Added my youtube channel's RSS feed
planetxamarin/planetxamarin pull request #699
Opened 2020-11-07 13:42 UTC by DamienDoumer

I updated my description and added the RSS feed of my youtube channel to my Author's class.

By sending this pull request to add my blog I verify that I adhere to the Planet Xamarin blog guidelines (please check each item that applies):

- [x] I have a valid blog & RSS URL, both using HTTPS :lock: with a valid certificate
- [x] I host NO malicious or offensive content on the blog (including photos, swearing, etc.)
- [x] My blog is active with at least 3 Xamarin related blog posts in the last 6 months
- [x ] In addition to the previous guideline; it should be apperant that the blog is active for a longer period of time and the posts on it are not fabricated in a small amount of time to comply to the '3 posts in last 6 months' guideline.
- [x] I have applied a filter (Optional: if blog is only about Xamarin or you use `xamarin` in the title or categories in your blog posts)
- [x] I have added my Author class to the csproj file
- [x] I have implemented `IAmACommunityMember` or one of the other derivatives
- [x ] I understand, if I delete my blog, I will be deleted from Planet Xamarin
- [x] I understand, my blog may be removed at any time if any of these guidelines are broken.
- [x] The submitted blog is not owned by a company which sole purpose it is to advertise a product of productline.

2020-11-09 07:42 UTC, Cheesebaron requested changes

2020-11-09 07:42 UTC, Cheesebaron commented on src/Firehose.Web/Authors/DamienDoumer.cs
> +    public class DamienDoumer : IAmACommunityMember, IFilterMyBlogPosts
```suggestion
    public class DamienDoumer : IAmACommunityMember
```

2020-11-11 00:56 UTC, DamienDoumer commented on src/Firehose.Web/Authors/DamienDoumer.cs
> +		}
I just removed it.

2020-11-11 06:49 UTC, Cheesebaron approved these changes

2020-11-11 06:50 UTC, merged